function trackers = configTrackers(trk_sign)
% 相关的tracker内容
% 续在最后往下添加, 添加完请补全注释
% 避免混乱出现下次找不到
% Fuling LIN, 01-Feb-2020

% trk_sign 对应组合
%   0 - 全部跟踪器模式
%   1 - 测试模式(最好是单独自己一个跟踪器)
%   2 - 某个期刊-组合1
%   3 - 某个期刊-组合2
%   ...

if nargin < 1
    trk_sign = 0; % 默认选择已有的全部跟踪器
end
switch trk_sign
    case 0
        %% 0 - 全部跟踪器模式
        trackers = {
            struct('name','KCF_LinearHog','namePaper','DCF'),...
            struct('name','KCF_GaussHog','namePaper','KCF'),...
            struct('name','DSST','namePaper','DSST'),...
            struct('name','CoKCF','namePaper','CoKCF'),...
            struct('name','BACF','namePaper','BACF'),...
            struct('name','SAMF','namePaper','SAMF'),...
            struct('name','SAMF_CA','namePaper','SAMF\_CA'),...
            struct('name','Staple','namePaper','Staple'),...
            struct('name','Staple_CA','namePaper','Staple\_CA'),...
            struct('name','SRDCF','namePaper','SRDCF'),...
            struct('name','SRDCFdecon','namePaper','SRDCFdecon'),...
            struct('name','CF2','namePaper','CF2'),...
            struct('name','MCCT','namePaper','MCCT'),...
            struct('name','MCCT_H','namePaper','MCCT\_H'),...
            struct('name','CCOT','namePaper','CCOT'),...
            struct('name','CSRDCF','namePaper','CSRDCF'),...
            struct('name','STRCF','namePaper','STRCF'),...
            struct('name','DeepSTRCF','namePaper','DeepSTRCF'),...
            struct('name','ECO_gpu','namePaper','ECO'),...
            struct('name','ECO_HC','namePaper','ECO-HC'),...
            struct('name','TADT','namePaper','TADT'),...
            struct('name','IBCCF','namePaper','IBCCF'),...
            struct('name','UDT','namePaper','UDT'),...
            struct('name','fDSST','namePaper','fDSST'),...
            struct('name','KCC','namePaper','KCC'),...
            struct('name','UDTplus','namePaper','UDT+'),...
            struct('name','MCPF','namePaper','MCPF'),...
            };
    case 1
        %% 1 - 测试模式(最好是单独自己一个跟踪器)
        trackers = {
            struct('name','KBiCF','namePaper','TB-BiCF'),...
            };
    case 2
        %% 2 - 某个期刊-组合1
        trackers = {
            struct('name','KCF_GaussHog','namePaper','KCF'),...
            struct('name','DSST','namePaper','DSST'),...
            struct('name','BACF','namePaper','BACF'),...
            struct('name','SAMF','namePaper','SAMF'),...
            struct('name','Staple_CA','namePaper','Staple\_CA'),...
            struct('name','SRDCF','namePaper','SRDCF'),...
            struct('name','SRDCFdecon','namePaper','SRDCFdecon'),...
            struct('name','MCCT_H','namePaper','MCCT\_H'),...
            struct('name','CSRDCF','namePaper','CSR-DCF'),...
            struct('name','STRCF','namePaper','STRCF'),...
            struct('name','ECO_HC','namePaper','ECO-HC'),...
            struct('name','fDSST','namePaper','fDSST'),...
            struct('name','KCC','namePaper','KCC'),...
            struct('name','Staple','namePaper','Staple'),...
            struct('name','BiCF','namePaper','BiCF'),...
            struct('name','KBiCF','namePaper','\bf{TB-BiCF}'),...
            };
    case 3
        %% 3 - att_bar_plot
        trackers = {
            struct('name','TB-BiCF','namePaper','TB-BiCF'),...
            struct('name','BiCF','namePaper','BiCF'),...
            struct('name','STRCF','namePaper','STRCF'),...
            struct('name','CSR-DCF','namePaper','CSR-DCF'),...
            struct('name','ECO-HC','namePaper','ECO-HC'),...
            };
    case 4
        %% 4 - att_bar_plot 带平均速度
        trackers = {
            struct('name','TB-BiCF','namePaper','TB-BiCF (46.8 FPS)'),...
            struct('name','BiCF','namePaper','BiCF (45.4 FPS)'),...
            struct('name','STRCF','namePaper','STRCF (14.0 FPS)'),...
            struct('name','CSR-DCF','namePaper','CSR-DCF (12.1 FPS)'),...
            struct('name','ECO-HC','namePaper','ECO-HC (69.3 FPS)'),...
            };
    otherwise
        %%
        error('警告: 请在configTrackers内组合跟踪器!');
end