function plotDrawStyle = plotSetting(sign)

switch sign
    case 0
        plotDrawStyle={   
            struct('color',[1,0,0],'lineStyle','-'),...
            struct('color',[0,1,0],'lineStyle','-'),...
            struct('color',[0,0,1],'lineStyle','-'),...
            struct('color',[0,0,0],'lineStyle','-'),...%    struct('color',[1,1,0],'lineStyle','-'),...%yellow
            struct('color',[1,0,1],'lineStyle','-'),...%pink
            struct('color',[0,1,1],'lineStyle','-'),...
            struct('color',[0.5,0.5,0.5],'lineStyle','-'),...%gray-25%
            struct('color',[136,0,21]/255,'lineStyle','-'),...%dark red
            struct('color',[255,127,39]/255,'lineStyle','-'),...%orange
            struct('color',[0,162,232]/255,'lineStyle','-'),...%Turquoise
            struct('color',[163,73,164]/255,'lineStyle','-'),...%purple    %%%%%%%%%%%%%%%%%%%%
            struct('color',[1,0,0],'lineStyle','--'),...
            struct('color',[0,1,0],'lineStyle','--'),...
            struct('color',[0,0,1],'lineStyle','--'),...
            struct('color',[0,0,0],'lineStyle','--'),...%    struct('color',[1,1,0],'lineStyle','--'),...%yellow
            struct('color',[1,0,1],'lineStyle','--'),...%pink
            struct('color',[0,1,1],'lineStyle','--'),...
            struct('color',[0.5,0.5,0.5],'lineStyle','--'),...%gray-25%
            struct('color',[136,0,21]/255,'lineStyle','--'),...%dark red
            struct('color',[255,127,39]/255,'lineStyle','--'),...%orange
            struct('color',[0,162,232]/255,'lineStyle','--'),...%Turquoise
            struct('color',[163,73,164]/255,'lineStyle','--'),...%purple    %%%%%%%%%%%%%%%%%%%
            struct('color',[1,0,0],'lineStyle','-.'),...
            struct('color',[0,1,0],'lineStyle','-.'),...
            struct('color',[0,0,1],'lineStyle','-.'),...
            struct('color',[0,0,0],'lineStyle','-.'),...%    struct('color',[1,1,0],'lineStyle',':'),...%yellow
            struct('color',[1,0,1],'lineStyle','-.'),...%pink
            struct('color',[0,1,1],'lineStyle','-.'),...
            struct('color',[0.5,0.5,0.5],'lineStyle','-.'),...%gray-25%
            struct('color',[136,0,21]/255,'lineStyle','-.'),...%dark red
            struct('color',[255,127,39]/255,'lineStyle','-.'),...%orange
            struct('color',[0,162,232]/255,'lineStyle','-.'),...%Turquoise
            struct('color',[163,73,164]/255,'lineStyle','-.'),...%purple
            };
    case 1
        plotDrawStyle={   
            struct('color',[1,0,0],'lineStyle','-'),...
            struct('color',[0,0,0],'lineStyle','-'),...
            struct('color',[1,0,1],'lineStyle','-'),...%pink
            struct('color',[0,1,0],'lineStyle','-'),...
            struct('color',[0,0,1],'lineStyle','-'),...
            };
    case 2
        plotDrawStyle={   
            struct('color',[1,0.42,0.42],'lineStyle','-'),...
            struct('color',[1,0.79,0.34],'lineStyle','-'),...
            struct('color',[1,0.62,0.95],'lineStyle','-'),...
            struct('color',[0.28,0.86,0.98],'lineStyle','-'),...%    struct('color',[1,1,0],'lineStyle','-'),...%yellow
            struct('color',[0.11,0.82,0.63],'lineStyle','-'),...%pink
            };
    case 3
        plotDrawStyle={   
            struct('color',[213, 62, 79]/255,'lineStyle','-'),...
            struct('color',[253, 174, 97]/255,'lineStyle','-'),...
            struct('color',[255, 255, 191]/255,'lineStyle','-'),...
            struct('color',[171, 221, 164]/255,'lineStyle','-'),...%    struct('color',[1,1,0],'lineStyle','-'),...%yellow
            struct('color',[50, 136, 189]/255,'lineStyle','-'),...%pink
            };
end